/**
 * Add settings for the module.
 *
 * @return {Array} The settings for the module.
 */
export default async () => {
  return [
    {
      id: 'favorite-setups.show-mobile-favorites',
      title: 'Include mobile favorites',
      default: false,
    },
    {
      id: 'favorite-setups.use-generated-names',
      title: 'Use generated names for setups',
      description: 'Names are generated by AI using each setup’s items and location.',
      default: true,
    },
  ];
};
