import { RAW_LOOT_INTRO_PHRASES } from '../../../shared/loot-intros';

import defineRules from './define';

export default defineRules('other', [
  ['I should hunt and catch a Relic Hunter or visit a Cartographer to obtain a new Treasure Map!', ''],
  ['hunt and catch a Relic Hunter or ', 'I can '],
  ['Treasure Map!', 'Treasure Map.'],
  [', causing my trap to glimmer with a magnificent shine', ''],
  [', causing my trap to sparkle with a fiendish glow', ''],
  [', causing my trap to spark with lightning', ''],
  ['(Local Time)', ''],
  ['and your item(s) have been', ''],
  [':</b><br>', '</b> '],
  [/<a href="receipt\.php.+?view receipt<\/a>/i, ''],
  ['me:<br>', 'me '],
  [
    /i should tell my friends to check .+? during the next .+? to catch one!/i,
    'She',
    { classes: ['relicHunter_catch'] },
  ],
  ['Luckily she was not interested in my cheese or charms.', ''],
  [/i can go to my .+? to open it/i, ''],
  ['The mouse stole', ' The mouse stole'],
  ['Chest, I can', 'Chest, '],
  ['<br>I should ', 'I can '],
  ['<br>I can ', 'I can '],
  [' I replaced my bait since it seemed to be stale.', ''],
  ['*POP* Your Unstable Charm pops off your trap and has', 'My Unstable Charm'],
  ['You quickly add it to your inventory!', ''],
  ['I quickly added it to my inventory!', ''],
  [' burned out and left behind ', ' turned into '],
  [' a elusive ', ' a '],
  ['I moved forward a whopping', 'I moved forward'],
  ['in search of more loot', ''],
  ['or I can return to the', 'or return to the'],
  [' and begin a new expedition', ''],
  [' ate a piece of cheese without setting off my trap.', ' stole my cheese.'],
  ['slowly collapsed into itself with a powerful force, compressing mist in the air into an ', 'compressed mist in the air into an '],
  ['Your S.U.P.E.R. Scum Scrubber scrubbed the mouse clean and found ', 'My trap found an extra '],
  ['You scrubba-lubba-dub-dubbed your barrel and refined ', 'I refined '],
  ['an additional 1 ', 'an additional '],
  [', and ', ' and '],
  ['My tower\'s ', 'My '],
  ['Energy Cannon', 'cannon'],
  ['before it could even touch my cheese!', ''],
  ['The mouse dropped the following prize', 'that dropped'],
  ['My Unstable Charm turned into', 'My Unstable Charm became'],
  ['My Condensed Creativity created additional loot:', 'My Condensed Creativity created an additional: '],
  ['The mouse stole an Ancient Relic and dropped a Relic Hunter Scroll Case', 'The mouse stole an Ancient Relic and dropped a Relic Hunter Scroll Case!'],
  ['*BLING*', '<span class="decoration"></span>'],
  ['Aura helped me find', 'Aura found'],
  ['processed  added', 'processed and added'],
  ['I have started a', 'I started a'],
  [/an additional:<br>/i, 'an additional ', { excludeClasses: ['festiveSpiritLootBoost'] }],
  ['<br></p><p>', '<p>'],
  ['<br><p>', '<p>'],
  ['My Farm to Table Bonus harvested an additional ', 'My Farm to Table Bonus harvested an additional: '],
  ['I can view other recipe', '<p class="double">I can view other recipe'],
  ['Here is the loot summary from my infiltration of', 'I looted the following from'],
  ['Trove. and received', 'Trove and received'],
  ['Lucky me, a prize mouse wandered by and fell for my trap!', 'A prize mouse fell into my trap!'],
  [/(\d+?,?\d*?) x /i, ' $1 ', { classes: ['shop_purchase'] }],
  ['In a flash of light my', 'My'],
  ['Chrome Dragon Slayer Cannon</a> found an additional ', 'Chome Dragon Slayer Cannon</a> found a '],
  ['Dragon Slayer Cannon</a> found an additional ', 'Dragon Slayer Cannon</a> found an extra '],
  ['I opened my harvest bin and retrieved the following yield: <br><br>From ', 'I opened my harvest bin and retrieved the following yield from '],
  ['My Slayer Aura found 1 extra ', 'My Slayer Aura found an extra '],
  ...RAW_LOOT_INTRO_PHRASES.map((phrase) => [phrase, 'I found']),
  [/i earned some extra loot:<br>• (\d+?) <(.+?)>enerchi<\/a> from my (.+?)<br>/i, 'My $3 gave me an additional $1<a href="https://www.mousehuntgame.com/item.php?item_type=combat_energy_stat_item" onclick="hg.views.ItemView.show(\'combat_energy_stat_item\'); return false;">Enerchi</a>.'],
  ['my Skyfarer\'s Oculus and discovered the following loot:', 'my Skyfarer\'s Oculus and discovered: '],
  ['focussed the light from my ', 'focused the light from my '],
  ['Queso Cannonstorm Base</a> blasted 5 <a class="" title="" href="https://www.mousehuntgame.com/item.php?item_type=amber_queso_stat_item" onclick="hg.views.ItemView.show(\'amber_queso_stat_item\'); return false;">Solidified Amber Queso</a> to smithereens, revealing', 'Queso Cannonstorm Base</a> revealed'],
  ['Queso Cannonstorm Base</a> blasted 5 <a class="" title="" href="https://www.mousehuntgame.com/item.php?item_type=amber_queso_stat_item" onclick="hg.views.ItemView.show(\'amber_queso_stat_item\'); return false;">Solidified Amber Queso</a> but nothing was found', 'Queso Cannonstorm Base</a> revealed nothing'],
  ['within the rubble!', ''],
  ['shatter brilliantly! I have', 'shatter brilliantly! <p>I have'],
  ['I used a Master Magus Wand to DOUBLE my Spell Force which caused it to shatter brilliantly!', 'I used a Master Magus Wand to double my Spell Force! It shattered in a brilliant explosion of light!'],
  ['Here is the summary of loot that I earned during my studies:<br><br>', 'I earned the following loot during my studies:'],
  ['The aura will last until', 'The aura expires on'],
  ['The last of the mist dissipated from the atmosphere.I can obtain more Mist Canisters and begin misting again.', 'The last of the mist dissipated.'],
  ['My Printing Press Base printed through a roll of', 'My Printing Press Base used a roll of'],
]);
