#! /usr/bin/env bash

# Get the power and minlucks from the Minlucks spreadsheet.
curl -s 'https://docs.google.com/spreadsheets/d/13hKjNDFTFR3rTkmQzyi3d4ZDOlQJUvTfWPDQemmFW_Y/gviz/tq?tqx=out:csv&gid=77067972' > minlucks.csv

# Convert the csv to json and replace the escaped quotes.
jq -cR 'split("\",\"")' minlucks.csv > minlucks2.csv
sed -i '' 's/\\"//g' minlucks2.csv
jq -csf scripts/csv2json.jq minlucks2.csv | jq > minlucks.json

# # Reformat the json to be an array of objects in the format {"<mouse>": {"power": <power>, "minlucks": [<minlucks>]}}
jq -s '.[0][] | {(.Mouse):{ arcane: .Arcane, draconic: .Draconic, forgotten: .Forgotten, hydro: .Hydro, physical: .Physical, shadow: .Shadow, tactical: .Tactical, law: .Law, rift: .Rift}}' minlucks.json > minlucks2.json
jq -s 'add' minlucks2.json > minlucks.json

mv minlucks.json src/data/mice-minlucks.json

rm minlucks.csv
rm minlucks2.csv
rm minlucks2.json
