#!/usr/bin/env bash

# Make sure we're in the root directory
cd "$(dirname "$0")/.." || exit

echo -n "upscaled-images.css"
curl --silent https://api.mouse.rip/upscaled-images.css --output src/modules/image-upscaling/upscaled-images.css
echo " ✓"

echo -n "upscaled-journal-theme-images.css"
curl --silent https://api.mouse.rip/upscaled-journal-theme-images.css --output src/modules/image-upscaling/upscaled-journal-theme-images.css
echo " ✓"

echo -n "upscaled-journal-icons.css"
curl --silent https://api.mouse.rip/journal-icons.css --output src/modules/better-journal/modules/journal-icons/journal-icons.css
echo " ✓"

echo -n "upscaled-journal-icons.css"
curl --silent https://api.mouse.rip/dark-mode-mice-images.css --output src/modules/native-dark-mode/styles/dark-mode-mice-images.css
echo " ✓"
