#! /usr/bin/env bash

if [ -f .env ]; then
  source .env
fi

version=$(jq -r .version package.json)

git tag -a "v$version" -m "Release v$version" || exit 1

git push origin main
git push origin "v$version"

bun run clean
bun run build:extension:chrome --release
bun run build:extension:firefox --release

bun run sentry-cli sourcemaps inject dist
bun run sentry-cli sourcemaps upload --release="$version" --project="mh-improved" dist
bun run sentry-cli releases new "$version" --project="mh-improved"
bun run sentry-cli releases finalize "$version" --project="mh-improved"

bun run build:zips
bun run build:userscript
bun run build:archive

gh release create "v$version" --title "MouseHunt Improved $version" --draft dist/chrome.zip dist/firefox.zip dist/*.user.js
